### ISSUE TITLE
Compilation issues after upgrading to Xcode 10.2

### ISSUE THREAD

**Issue by npvisual** [DeclarativeHub/Layoutless#7]
### Problem description
Been using Layoutless in my Views before upgrading to 10.2 with no issues. However after upgrading to 10.2, I get the following compilation errors : 

```
Cannot find interface declaration for 'ViewController', superclass of 'RegistrationViewController'; did you mean 'UIViewController'?

Cannot find interface declaration for 'ViewController', superclass of 'SchedulesController'; did you mean 'UIViewController'?
...
```

Those issues all appear in the Binder section of my code where I am defining extensions as per the [Binder Architecture](https://github.com/DeclarativeHub/TheBinderArchitecture#binder).

So, for example, in my View module, the RegistrationViewController defines : 

`public class RegistrationViewController: ViewController { ... }
`

and in the Binder module : 

`extension RegistrationViewController { ... }
`

I tried rebuilding each module separately (after clearing out the build cache), but to no avail.

Any ideas ?

**Comment by npvisual** [comment]
After fiddling around with the build settings, it looks like adding `Layoutless.framework` directly into the "Linked Frameworks and Libraries" of the View module itself solved the compilation issue.

**Comment by npvisual** [comment]
While I was actually able to compile at some point, I tried to recreate the steps to do that from my original workspace and it's still not working.

**Comment by npvisual** [comment]
Some more info : when I build against my iPhone X, I don't get any compilation issues. However when I build against a simulator I do get those compilation errors.

I tried running `xcrun simctl erase all` but that didn't do anything.

**Comment by srdanrasic** [comment]
I've tested the framework with Xcode 10.2 and it works properly. Is might be related to your project configuration. Do you have `import Layoutless` and are there any errors on that line?

**Comment by npvisual** [comment]
No error there. Whether it's in View or in the Binder module (which wasn't needed before) I can add the `import Layoutless` line and no error will show there (it even suggest that module as I am typing it).

I don't know if they changed something that would conflict with where / how Carthage compiles the framework dependencies. But it's definitely not resolving the ViewController dependency (despite the fact that the `@import Layoutless` is in the View-Swift.h of the module (generated by Xcode).

**Comment by npvisual** [comment]
Here, I was able to reproduce the problem in this [very simple app](https://github.com/npvisual/Xcode102Issue) and published it on GitHub.

The `View` framework (which imports `Layoutless`) compiles properly. But when you try and compile the `Binder` framework (which imports `View`) then it complains about not being able to find an interface for ViewController.

This was never an issue for me with the previous versions of Xcode.

![Screen Shot 2019-03-27 at 9 25 17 AM](https://user-images.githubusercontent.com/3268395/55083932-55f31a80-5072-11e9-94c7-d17b3e785503.png)

**Comment by npvisual** [comment]
If I build against my iPhone, instead of the simulator, then it compiles just fine : 

![Screen Shot 2019-03-27 at 9 35 07 AM](https://user-images.githubusercontent.com/3268395/55084915-c0588a80-5073-11e9-8417-6f8f39ced485.png)

**Comment by srdanrasic** [comment]
I'll check out the example app later. Seems to be something related ObjC. Try setting SWIFT_INSTALL_OBJC_HEADER build setting to NO in View.

**Comment by npvisual** [comment]
Yup. Apparently changing this for the `View` framework allows it to compile. Thanks !

What's interesting is that it wasn't a problem to compile for my iPhone, but it was for the simulator...

![Screen Shot 2019-03-27 at 10 18 19 AM](https://user-images.githubusercontent.com/3268395/55088492-cf423b80-5079-11e9-839f-9b50382abd44.png)

**Comment by npvisual** [comment]
The (other) app is now able to compile as well.
Feel free to close unless there's something more fundamental that's causing this.

Thanks @srdanrasic !

**Comment by srdanrasic** [comment]
Looks like there is new a behaviour / issue in Xcode 10.2. Check under [Build System / Known Issues](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes). 

This should be resolved in the next version of Carthage: https://github.com/Carthage/Carthage/pull/2723

Until then, I hope the above workaround works.

**Comment by srdanrasic** [comment]
Resolved in Carthage.
