### ISSUE TITLE
Problems with Swift 5.1 and Xcode 11.0 beta 4

### ISSUE THREAD

**Issue by ream88** [DeclarativeHub/Layoutless#10]
Installing Layoutless via Carthage using Xcode 11.0 beta 4 and Swift 5.1 results in the following error: 

```Building scheme "Layoutless-iOS" in Layoutless.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /path/to/app/Carthage/Checkouts/Layoutless/Layoutless.xcworkspace -scheme Layoutless-iOS -configuration Release -derivedDataPath /Users/mario/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11M374r/Layoutless/0.4.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/b_/n__v03ld5614t94z1y10nfqm0000gn/T/Layoutless SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /path/to/app/Carthage/Checkouts/Layoutless)
```

The log contains this lines at the bottom: 

```ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/mario/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11M374r/Layoutless/0.4.1/Build/Intermediates.noindex/ArchiveIntermediates/Layoutless-iOS/IntermediateBuildFilesPath/Layoutless.build/Release-iphoneos/Layoutless-iOS.build/Objects-normal/arm64/Binary/Layoutless normal arm64
(1 failure)
```

**Comment by ream88** [comment]
It worked with Xcode 11.0 beta 5, so I'm closing this! 😊
